[main]
# Tipografía (Asegúrate de tener una fuente Nerd instalada, cámbiala si usas otra)
font=JetBrainsMono Nerd Font:weight=bold:size=12
prompt="  "
icon-theme=Papirus-Dark
icons-enabled=yes

# Dimensiones y espaciado
lines=10
width=40
horizontal-pad=20
vertical-pad=20
inner-pad=5

# Comportamiento
layer=top
exit-on-keyboard-focus-loss=yes

[colors]
# Fuzzel usa el formato RRGGBBAA (Rojo, Verde, Azul, Alfa/Transparencia)
# Fondo oscuro semi-transparente
background=1e1e2ee6

# Texto general
text=cdd6f4ff

# Texto coincidente al buscar (El púrpura de tu Hyprland)
match=c678ddff

# Fondo de la opción seleccionada
selection=313244ff

# Texto de la opción seleccionada
selection-text=cdd6f4ff

# Texto coincidente en la opción seleccionada
selection-match=c678ddff

# Color del borde (El púrpura de tu Hyprland)
border=c678ddff

[border]
# Redondeo igual al de tus ventanas de Hyprland
radius=12
width=2
