set -g history-limit 50000
set -g default-terminal "tmux-256color"

set -g mouse on
set -g status-keys vi
set -g mode-keys vi
set -sg escape-time 10

set -gq allow-passthrough on
set -s set-clipboard external
set -as terminal-features ',ghostty:RGB'
set -as terminal-features ',xterm-256color:RGB'

set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind-key BSpace send-keys C-l \; run 'sleep 0.2' \; clear-history
bind m run "cut -c3- '#{TMUX_CONF}' | sh -s _toggle_mouse" \; display 'mouse #{?#{mouse},on,off}'
