set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "no"
set -g @catppuccin_pane_border_status "off"
set -g @catppuccin_pane_border_style "fg=#{@thm_surface_1}"
set -g @catppuccin_pane_active_border_style "fg=#{@thm_overlay_0}"

run-shell 'bash ~/.config/tmux/plugins/catppuccin/catppuccin.tmux'
