set -g status on
set -g status-position top
set -g status-justify centre
set -g status-left-length 0
set -g status-right-length 0
set -g window-status-separator "  "

set -gF status-style "bg=default,fg=#{@thm_fg}"
set -gF message-style "fg=#{@thm_crust},bg=#{@thm_lavender}"
set -gF mode-style "fg=#{@thm_crust},bg=#{@thm_lavender}"

set -g status-left ""
set -g status-right ""
set -g window-status-format "#[fg=#{@thm_sky},bg=default]#[fg=#{@thm_crust},bg=#{@thm_sky}]   #I #W   #[fg=#{@thm_sky},bg=default]#[default]"
set -g window-status-current-format "#[fg=#{@thm_pink},bg=default]#[fg=#{@thm_crust},bg=#{@thm_pink},bold]   #I #W   #[fg=#{@thm_pink},bg=default]#[default]"
