# Editor / pager
mime ^text,  label editor = lvim -- "$@"
mime ^text,  label pager  = "$PAGER" -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|md|yml|toml|lua = lvim -- "$@"

# Web
ext x?html?, has google-chrome, X, flag f = google-chrome -- "$@"
ext x?html?, has chromium,      X, flag f = chromium -- "$@"
ext x?html?, has firefox,       X, flag f = firefox -- "$@"
ext x?html?, has open,          X, flag f = open -- "$@"
ext x?html?, has xdg-open,      X, flag f = xdg-open -- "$@"

# PDF / Office
ext pdf, has zathura,   X, flag f = zathura -- "$@"
ext pdf, has evince,    X, flag f = evince -- "$@"
ext pdf, has open,      X, flag f = open -- "$@"
ext pdf, has xdg-open,  X, flag f = xdg-open -- "$@"
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw, has libreoffice = libreoffice -- "$@"
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw, has open = open -- "$@"
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw, has xdg-open = xdg-open -- "$@"

# Multimedia / images
mime ^video|audio, has mpv,      X, flag f = mpv -- "$@"
mime ^video|audio, has vlc,      X, flag f = vlc -- "$@"
mime ^video|audio, has open,     X, flag f = open -- "$@"
mime ^video|audio, has xdg-open, X, flag f = xdg-open -- "$@"
mime ^image, has nsxiv,          X, flag f = nsxiv -a -- "$@"
mime ^image, has sxiv,           X, flag f = sxiv -a -- "$@"
mime ^image, has feh,            X, flag f = feh -- "$@"
mime ^image, has open,           X, flag f = open -- "$@"
mime ^image, has xdg-open,       X, flag f = xdg-open -- "$@"

# Archives
ext 7z|ace|ar|arc|bz2?|cab|cpio|deb|gz|iso|jar|rar|tar|tgz|xz|zip, has atool = atool --list --each -- "$@" | "$PAGER"
ext 7z|ace|ar|arc|bz2?|cab|cpio|deb|gz|iso|jar|rar|tar|tgz|xz|zip, has bsdtar = bsdtar --list --file "$1"

# Terminal
mime ^ranger/x-terminal-emulator, has kitty = kitty -- "$@"
mime ^ranger/x-terminal-emulator, has alacritty = alacritty -- "$@"
mime ^ranger/x-terminal-emulator, has footclient = footclient -- "$@"
mime ^ranger/x-terminal-emulator, has open = open -a Terminal.app "$@"
mime ^ranger/x-terminal-emulator, has x-terminal-emulator = x-terminal-emulator -- "$@"

# Generic open and trash
label open, has open = open -- "$@"
label open, has xdg-open = xdg-open -- "$@"
label trash, has trash-put = trash-put -- "$@"
label trash, has gio = gio trash -- "$@"
label trash, has kioclient5 = kioclient5 move -- "$@" trash:/
label trash, has open = mv -- "$@" ~/.Trash
label trash = mkdir -p ~/.local/share/Trash/files && mv -- "$@" ~/.local/share/Trash/files
