# --- Variables de Entorno ---
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
env = GDK_SCALE,2
env = XCURSOR_SIZE,32
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# XDG y Wayland
env = PATH,/home/elsadeveloper/.ghcup/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11

# --- Configuración de Cursor ---
env = HYPRCURSOR_THEME,Rose-Pine
env = HYPRCURSOR_SIZE,24
