# =============================================================================
# HYPRLAND KEYBINDINGS - MODULAR EDITION
# =============================================================================

source = ~/.config/hypr/conf/keybinds/variables.conf
source = ~/.config/hypr/conf/keybinds/generated.conf
