# =============================================================================
# 🔊 CONTROLES HARDWARE (l=Locked, e=Repeat)
# =============================================================================

bindle = , XF86AudioRaiseVolume,  exec, ~/.config/hypr/scripts/multimedia/volume.hs up
bindle = , XF86AudioLowerVolume,  exec, ~/.config/hypr/scripts/multimedia/volume.hs down
bindl  = , XF86AudioMute,         exec, ~/.config/hypr/scripts/multimedia/volume.hs mute
bindle = , XF86MonBrightnessUp,   exec, brightnessctl set 5%+ && notify-send -e -h string:x-canonical-private-synchronous:sys-notify -u low "Brillo" "Aumentando" -i display-brightness
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%- && notify-send -e -h string:x-canonical-private-synchronous:sys-notify -u low "Brillo" "Reduciendo" -i display-brightness-low
