# =============================================================================
# 🔊 CONTROLES HARDWARE (Flags: l=Locked, e=Repeat)
# =============================================================================

bindle = , XF86AudioRaiseVolume,  exec, $vol_hs up
bindle = , XF86AudioLowerVolume,  exec, $vol_hs down
bindl  = , XF86AudioMute,         exec, $vol_hs mute
bindle = , XF86MonBrightnessUp,   exec, $bri_up
bindle = , XF86MonBrightnessDown, exec, $bri_down
