# =============================================================================
# 🚀 LANZADORES - Apps principales con su letra inicial
# =============================================================================

bind = SUPER, Return, exec, ghostty                                                                                                             # Terminal
bind = SUPER, Space,  exec, rofi -show drun                                                                                                     # Menú de apps
bind = SUPER, B,      exec, brave                                                                                                               # Browser
bind = SUPER, V,      exec, ghostty -e lvim                                                                                                     # Vim / Editor
bind = SUPER, Y,      exec, brave --new-window https://youtube.com && notify-send -e -h string:x-canonical-private-synchronous:sys-notify -u low "YouTube" "Abriendo en ventana nueva" -i youtube  # YouTube
