# =============================================================================
# 🚀 LANZADORES (Letra inicial de la App/Acción)
# =============================================================================

bind = $mainMod, Return, exec, $terminal             # [Return] -> Terminal
bind = $mainMod, Space,  exec, $menu                 # [Espacio] -> Menú global
bind = $mainMod, B,      exec, $browser              # [B]rowser
bind = $mainMod, V,      exec, $editor               # [V]im / Editor
bind = $mainMod, Y,      exec, $yt_cmd               # [Y]outube
