# =============================================================================
# 🧠 SCRIPTS Y MENÚS (Mod = Acción directa)
# =============================================================================

bind = $mainMod, A, exec, $scrDir/ai/ai_menu.hs                  # [A]I
bind = $mainMod, S, exec, $scrDir/system/system_utils.hs          # [S]istema
bind = $mainMod, M, exec, $scrDir/multimedia/multimedia_menu.hs   # [M]ultimedia
bind = $mainMod, N, exec, $scrDir/network/network_menu.hs         # [N]etwork
bind = $mainMod, P, exec, $screenshot                             # [P]rint / Captura
bind = $mainMod, D, exec, $scrDir/productivity/todo.hs            # to[D]o List
bind = $mainMod, W, exec, $scrDir/system/window_manager.hs        # [W]indows
bind = $mainMod, O, exec, $notif -t -sw                           # N[O]tificaciones
