# =============================================================================
# 🛠️ ESTADO DEL SISTEMA (Shift para acciones de cambio)
# =============================================================================

bind = $mainMod SHIFT, R, exec, $reload_cmd
bind = $mainMod SHIFT, W, exec, $bar_reset
bind = $mainMod SHIFT, Q, exec, $logout
bind = $mainMod CTRL SHIFT, Q, exit                  # Salida forzosa
