# =============================================================================
# VARIABLES DE APLICACIONES, MACROS Y SCRIPTS
# =============================================================================

# --- Variables de Aplicaciones ---
$mainMod    = SUPER
$terminal   = ghostty
$browser    = brave
$editor     = $terminal -e lvim
$menu       = rofi -show drun
$notif      = swaync-client
$logout     = wlogout
$waybar     = waybar
$scrDir     = ~/.config/hypr/scripts

# --- Motor de Notificaciones (Sincronizado para evitar spam) ---
$sysNotif   = notify-send -e -h string:x-canonical-private-synchronous:sys-notify -u low

# --- Macros de Comandos (Acción + Notificación) ---
$yt_cmd     = $browser --new-window https://youtube.com && $sysNotif "YouTube" "Abriendo en ventana nueva" -i youtube
$reload_cmd = hyprctl reload && $sysNotif "Sistema" "Configuración Recargada" -i software-update-available
$bar_reset  = pkill $waybar; $waybar & disown && $sysNotif "Waybar" "Barra de estado reiniciada" -i dropboxstatus-logo

# Hardware (Audio/Brillo)
$vol_up     = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && $sysNotif "Volumen" "Subiendo" -i audio-volume-high
$vol_down   = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $sysNotif "Volumen" "Bajando" -i audio-volume-low
$vol_mute   = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $sysNotif "Audio" "Silencio (Mute)" -i audio-volume-muted
$bri_up     = brightnessctl set 5%+ && $sysNotif "Brillo" "Aumentando" -i display-brightness
$bri_down   = brightnessctl set 5%- && $sysNotif "Brillo" "Reduciendo" -i display-brightness-low

# --- Variables de Scripts ---
$vol_hs     = $scrDir/multimedia/volume.hs
$screenshot = $scrDir/multimedia/screenshot.hs
