from .development import (
    dev_open_in_lvim,
    dev_open_in_lvim_root,
    dev_tmux_lvim,
    dev_tmux_project,
    dev_tmux_split_lvim,
    open_terminal_here,
)
from .files import (
    bulk_rename_lvim,
    downloads_recent,
    extract_here_smart,
    my_edit,
    ocr_to_clipboard,
    smart_open,
    smart_trash,
)
from .git import copy_relative_path, copy_repo_path, git_file_actions
from .notes import notes_actions
from .personal import (
    go_desktop,
    go_dev,
    go_documents,
    go_dotfiles,
    go_downloads,
    go_home,
    go_music,
    go_notes,
    go_pictures,
    go_projects,
    go_screenshots,
    go_videos,
    go_wallpapers,
)
from .search import fzf_content_search, fzf_select, spotlight, z
from .workflow import (
    file_diagnostics,
    move_selection_by_type,
    normalize_filenames,
    open_with_context,
    places_menu,
    run_project_task,
)
from .wm_shared import (
    calculator_menu,
    clipboard_menu,
    english_menu,
    files_menu,
    keybind_cheatsheet,
    multimedia_menu,
    projects_menu,
    scratchpad_menu,
    session_menu,
    system_info_menu,
    todo_menu,
    workspace_menu,
)


COMMAND_CLASSES = [
    my_edit,
    fzf_select,
    z,
    fzf_content_search,
    spotlight,
    smart_open,
    smart_trash,
    ocr_to_clipboard,
    dev_open_in_lvim,
    dev_open_in_lvim_root,
    dev_tmux_lvim,
    dev_tmux_project,
    dev_tmux_split_lvim,
    open_terminal_here,
    projects_menu,
    clipboard_menu,
    files_menu,
    system_info_menu,
    session_menu,
    workspace_menu,
    scratchpad_menu,
    multimedia_menu,
    downloads_recent,
    copy_relative_path,
    copy_repo_path,
    git_file_actions,
    extract_here_smart,
    bulk_rename_lvim,
    go_home,
    go_downloads,
    go_documents,
    go_desktop,
    go_projects,
    go_dotfiles,
    go_notes,
    go_dev,
    go_pictures,
    go_screenshots,
    go_wallpapers,
    go_music,
    go_videos,
    todo_menu,
    keybind_cheatsheet,
    calculator_menu,
    english_menu,
    notes_actions,
    places_menu,
    run_project_task,
    normalize_filenames,
    move_selection_by_type,
    open_with_context,
    file_diagnostics,
]


def export_command_classes():
    return {command.__name__: command for command in COMMAND_CLASSES}
